# Generated by Django on 2026-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
